### ISSUE TITLE
Your published version includes react-transform-hmr

### ISSUE THREAD

**Issue by jquense** [maslianok/react-resize-detector#1]
Hey there,

I went to try this out, but I couldn't without installing react-transform-hmr. It looks like your test and example build is leaking into your production build, since the published code probably should not have hot loading wrappings in it.

Thanks

**Comment by maslianok** [comment]
Fixed.
@jquense Thanks for the feedback!

**Comment by pdf** [comment]
Does not appear to be fixed on npm.
