### ISSUE TITLE
Resize not being detected when rendering component is changed (HOC). 

### ISSUE THREAD

**Issue by misaelgaray** [maslianok/react-resize-detector#101]
When rendering multiple components it just detects resizing in the first one. If, for some reason, you start rendering another one, it just not detects the resizing in the second one. This happens using HOC. Example.
`
      render(){
   if(!this.state.show){
			return <button onClick={this.handleShow}>Show</button>
		}
		return <h1>Hey there</h1>;
}
`

**Comment by maslianok** [comment]
Yes, you're right. 

It happens because `resize-detector` caches the element on the first render in `componentDidMount`.

**Comment by maslianok** [comment]
Fixed in v.5.1.0

Please upgrade to the last version from npm

**Comment by zarv1k** [comment]
@maslianok could you please remove [console](https://github.com/maslianok/react-resize-detector/blob/master/src/components/ResizeDetector.js#L78) [logs](https://github.com/maslianok/react-resize-detector/blob/master/src/components/ResizeDetector.js#L82)?

**Comment by maslianok** [comment]
lol :) done

**Comment by zarv1k** [comment]
@maslianok it seems that console logs still leave in lib (build results) :). Could you please rebuild and publish version without logs?

**Comment by maslianok** [comment]
@zarv1k omg, sorry for the inconvenience :( 

That's how it works when you're rushing...

Fixed in v5.1.3

**Comment by zarv1k** [comment]
@maslianok it happens :) Thank you!
