### ISSUE TITLE
lodash-es has critical security issue 

### ISSUE THREAD

**Issue by slangberg** [maslianok/react-resize-detector#103]
lodash-es is stuck a with lodash version 4.17.15 that contains the  Prototype Pollution issue found in https://snyk.io/vuln/SNYK-JS-LODASH-450202. This unused dependency  means that automated security software will not allow the use of this package. This dependency  doesn't seem to be used as all utils import from lodash

**Comment by maslianok** [comment]
It is used in esm builds.

But I agree that it's not an option for us to keep such a library in the dependencies list.

It's removed in v5.2.0.
