### ISSUE TITLE
Height is undefined with renderProps - HOC and component implementation 

### ISSUE THREAD

**Issue by ItayTur** [maslianok/react-resize-detector#106]
hey,
thank you for this lib.
when using renderProps I'm only getting the height when the component mounts, and it is always undefined.
when i change the component to span with the height printed inside it is shown.

```
<ReactResizeDetector handleWidth handleHeight>
      {
        ({ width, height }) =>
          {
            return <td ref={cellRef}>
            <CalendarCell
              className={st(classes.CalendarCell, { timeType, isWeekEnd, isStretchable })}
              title={timeToDisplay}
              timeType={timeType}
              current={current}
              alignment={alignment}
              stretchable={isStretchable}
            >
              {eventsToShow && eventsToShow(height)}
            </CalendarCell>
          </td>}
      }
    </ReactResizeDetector>
```

this is the method that suppose to use the height
```
const eventsToShow = events.length ? containerHeight => {

    debugger;
    return render(
      {
        time,
        events,
        popperPlacement,
        popperStyle,
        containerHeight
      })
  } :
    null;
```

i tried with the HOC and still faced the same issue

**Comment by ItayTur** [comment]
The problem was that the height of the td has no `height` only `padding-top: 100%` for 1:1 ratio. so the height is always 0.
thx again

**Comment by ItayTur** [comment]
is there a way to fire the event when the `padding` is in control of the height ?

**Comment by ItayTur** [comment]
so since `padding-top` in percentage is calculated by `width`, i just use `width` instead and there for detect the `height` change with ratio 1:1

**Comment by maslianok** [comment]
yes, you're right, you should listen to `width` changes.

Great to see how your solution evolves and finally you get the point 😄 👍
