### ISSUE TITLE
Monitoring child component 

### ISSUE THREAD

**Issue by slava-lu** [maslianok/react-resize-detector#107]
I wanted to update your HOC example with the parent component (**ParentDiv**):

```
import { withResizeDetector } from 'react-resize-detector';

const CustomComponent = ({ width, height, targetRef }) => 
<ParentDiv>
  <div ref={targetRef}>{`${width}x${height}`}</div>
</ParentDiv>

export default withResizeDetector(CustomComponent);
```
But it did not work for me because I still get the width of the ParentDiv, rather than the child div I attach ref to.

**Comment by slava-lu** [comment]
Looks like I just needed to wrap a child component in `React.forwardRef`

**Comment by maslianok** [comment]
Sorry for the late response.
I don't think you were waiting for my help since you found the correct answer for your problem :)

`forwardRef` is the function you are searched for ))
