### ISSUE TITLE
Missing type annotations for children

### ISSUE THREAD

**Issue by redwoodfavorite** [maslianok/react-resize-detector#110]
Using v5 with latest type definitions: There are no special annotations for children so the args passed to the child function are of `any` type.

![image](https://user-images.githubusercontent.com/5566649/100674725-77fa7100-331a-11eb-84f4-1b3a31fa37cb.png)
`Binding element 'width' implicitly has an 'any' type.`

With a union type definition for valid `props.children` you could write an annotation for the argument passed to the child function of `ReactResizeDetector`.

Seems like a nice feature to have considering this is one of the recommended patterns!  Let me know if you'd like me to help with this.

**Comment by maslianok** [comment]
The library has been rewritten in TypeScript.

The bug should be resolved in v6.0.0-alpha.1.
Please check and let me know if the error still exists.

A stable release will be published in a few days.
