### ISSUE TITLE
Version 6.0.1-rc.1 break in SSR page (Next Js)

### ISSUE THREAD

**Issue by nonusae** [maslianok/react-resize-detector#116]
I used v.6.0.1-rc.1 and v6.0.1-alpha.1 in my nextJS application and got an error when navigate to page with getInitialProps.

After searching a while I found a solution in [this issue](https://github.com/maslianok/react-resize-detector/issues/93). After downgrade to `v.5.0.6` everything work perfectly.

I will attach the screenshoot of an error.
<img width="1015" alt="Screen Shot 2564-01-12 at 03 12 40" src="https://user-images.githubusercontent.com/6436298/104233224-15050980-5484-11eb-8774-5c7a6c67a542.png">

**Comment by maslianok** [comment]
Yeah, I see the problem.

In v6.0.0 we've removed ResizeObserver polyfill since most browser support it natively nowadays. But we have to add some additional conditions to not process it on server side.

Will be fixed in the next release

**Comment by maslianok** [comment]
@nonusae can you please try 6.0.1-rc.2 ?

**Comment by nonusae** [comment]
@maslianok Work perfectly with `6.0.1-rc.3`. 🎉
