### ISSUE TITLE
Remove console.log debug statements

### ISSUE THREAD

**Issue by shauntrennery** [maslianok/react-resize-detector#125]
https://github.com/maslianok/react-resize-detector/blob/fbeff5dc49a0e0baa670217f4635e540b96cb6e0/src/utils.ts#L38

**Comment by Robloche** [comment]
Plus same file, line 40:
https://github.com/maslianok/react-resize-detector/blob/fbeff5dc49a0e0baa670217f4635e540b96cb6e0/src/utils.ts#L40

**Comment by maslianok** [comment]
Ah, sh*t :(

Merged, I’ll push a new version to npm in 2 hours.

thanks for the PR :)

**Comment by maslianok** [comment]
Fixed in v6.1.1

Sorry for that folks
