### ISSUE TITLE
Will be good to add ability to pass ResizeObserver options

### ISSUE THREAD

**Issue by whiteand** [maslianok/react-resize-detector#127]
Look at: [Resize Observer Options](https://drafts.csswg.org/resize-observer/#resize-observer-interface)

Will be good to be able to define which size change we want to detect

**Comment by maslianok** [comment]
I didn't even know that ResizeObserver has additional parameters.

I don't think it's supported by any browser or polyfill, isn't it?

**Comment by whiteand** [comment]
@maslianok 
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe

**Comment by maslianok** [comment]
Agree, good idea! Thanks for the suggestion 👍 

I think it may be an additional property. Something like

```js
observerBoxModel: 'content-box' | 'border-box' | 'device-pixel-content-box'

// and later on

const resizeObserver = new window.ResizeObserver(resizeHandler.current, { box: observerBoxModel });
```

Can you make a PR with these changes?

**Comment by whiteand** [comment]
If no one will make it before me, I can try to do it tomorrow
@maslianok

**Comment by maslianok** [comment]
Thank you @whiteand 

I'm going to publish a new version tomorrow

**Comment by maslianok** [comment]
Published in v6.5.0

Thanks again for your efforts

**Comment by whiteand** [comment]
@maslianok readme.md contains `observeOptions` instead of `observerOptions`

**Comment by maslianok** [comment]
@whiteand 
thanks, updated...

Sorry, I forgot to mention that I changed the prop name a bit.  
I hope you're fine with the new name :)

**Comment by alienzhangyw** [comment]
This option is not working as expected, I still get content-box size with option 'box'  been set to 'border-box'.
I'm using react-resize-detector/build/withPolyfill.

**Comment by maslianok** [comment]
We're using the pattern described here https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe

```js
resizeObserver.observe(divElem, { box : 'border-box' });
```

Nothing fancy or error-prone ([source code](https://github.com/maslianok/react-resize-detector/blob/master/src/ResizeDetector.tsx#L188))

The usage might look like

```js
withResizeDetector(CustomComponent, { observerOptions: { box : 'border-box' } });
```

Let me know if this doesn't work for you
