### ISSUE TITLE
useResizeDetector with targetRef - version 1.3.1

### ISSUE THREAD

**Issue by whplh** [maslianok/react-resize-detector#130]
Hi,
if have the following problem with the new targetRef:
If I use: 
`const {width, height} = useResizeDetector({targetRef: someRef})`
width and height are always undefined for my component
Whereas if I use:
`const {width, height} = useResizeDetector({targetRef: someRef, onResize: ()=>{}})`
I get the correct dimensions of the someRef component,.... which doesn't really make sense to me.
I suspect react-resize-detector is not reacting to ref changes properly.
Adding `ref.current` to the dependency array `[refreshMode, refreshRate, refreshOptions, handleWidth, handleHeight, onResize]` (which helps in my case) seems to be [wrong](https://github.com/facebook/react/issues/14387#issuecomment-455415008) and ["wrong"](https://github.com/facebook/react/issues/14387#issuecomment-493677168) 
Any ideas?
Cheers,

**Comment by maslianok** [comment]
Yeah, I see the problem...

`onResize` is an anonymous function. 
JS creates a new instance of this function every time the parent component rerenders. And, as a result, it triggers `useEffect` logic...

**Comment by maslianok** [comment]
After reading [this](https://github.com/facebook/react/issues/14387) thread I found that we probably use the wrong hook.

I think we should use `useLayoutEffect` instead of the `useEffect`.

Can you please try a new prerelease version v6.4.0-rc.0 with this update and confirm that it resolves your problem?

**Comment by whplh** [comment]
I tried v6.4.0-rc.0  - didn't work.
Looking (and playing around with the code) it's basically the same problem.
The useLayoutEffect would never know when the ref changes.

The way the refs are handled currently. Is not how it's supposed to be.
There probably shouldn't be any targetRef or any other ref you pass to a hook
 
To formulate more clearly what basically what would be needed here:

> Make sure the code in the useEffect/useLayout section
> runs again if one of the current dependency changes or if there is a change in the ref Element

**Comment by whplh** [comment]
So here is a suggestion I came up with:
(Be carefull, I used any in Typescript for you to figure it out =)
`import { useCallback, useState, useRef, MutableRefObject, useEffect } from 'react';

import { patchResizeHandler, createNotifier, isSSR, patchResizeHandlerType } from './utils';

import { Props, ReactResizeDetectorDimensions } from './ResizeDetector';

type resizeHandlerType = MutableRefObject<null | patchResizeHandlerType>;
interface returnType<RefType> extends ReactResizeDetectorDimensions {
  ref: MutableRefObject<null | RefType>;
}

interface FunctionProps<RefType> extends Props {
  targetRef?: MutableRefObject<null | RefType>;
}

function useResizeDetector<RefType extends Element = Element>(props: FunctionProps<RefType> = {}): any { // Todo replace any
  const {
    skipOnMount = false,
    refreshMode,
    refreshRate = 1000,
    refreshOptions,
    handleWidth = true,
    handleHeight = true,
    onResize
  } = props;

  const skipResize: MutableRefObject<null | boolean> = useRef(skipOnMount);
  const resizeHandler: resizeHandlerType = useRef(null);

  const [node, setNode] = useState<RefType>();
  const [size, setSize] = useState<ReactResizeDetectorDimensions>({
    width: undefined,
    height: undefined
  });

  useEffect( () => {
    if (isSSR()) {
      return;
    }
    
    const notifyResize = createNotifier(onResize, setSize, handleWidth, handleHeight);

    const resizeCallback: ResizeObserverCallback = entries => {
      if (!handleWidth && !handleHeight) return;

      entries.forEach(entry => {
        const { width, height } = (entry && entry.contentRect) || {};

        const shouldSetSize = !skipResize.current && !isSSR();
        if (shouldSetSize) {
          notifyResize({ width, height });
        }

        skipResize.current = false;
      });
    };

    resizeHandler.current = patchResizeHandler(resizeCallback, refreshMode, refreshRate, refreshOptions);

    const resizeObserver = new window.ResizeObserver(resizeHandler.current);

    if(!!node){
      resizeObserver.observe(node as Element);
    }

    return () => {
      resizeObserver.disconnect();
      const patchedResizeHandler = resizeHandler.current as any;
      if (patchedResizeHandler && patchedResizeHandler.cancel) {
        patchedResizeHandler.cancel();
      }
    };
  }, [refreshMode, refreshRate, refreshOptions, handleWidth, handleHeight, onResize, node]);

  const ref = useCallback(node => {
    if (node !== null) {
      setNode(node)
    }
  }, [setNode]);

  return { ref, ...size };
}

export default useResizeDetector;
`

**Comment by whplh** [comment]
Ah ok I had a look at the other thread. If the ref is need from within onResize, why not add it? ~> onResize(width, height, useRef(node))
Anyway. Let me know what you think. Cheers.

**Comment by maslianok** [comment]
Well, before diving deep into your suggestions let me clarify one more time: are you sure v6.4.0-rc.0 doesn't solve the problem you described in the initial issue?

Here is the code snippet that works perfectly in my case https://codesandbox.io/s/holy-rain-jjybk

**Comment by whplh** [comment]
Ok I will try to replicate the issue with an example on codesandbox.

**Comment by whplh** [comment]
Ok making the example also helped me understand the problem more clearly.
It's not just the new targetRef. It's a more general problem with the useResizeDetector Hook.
(Basically it's a bug which affects all components which refs are mutated during runtime of the application)

The most simple example I could think of, to replicate the bug :
https://codesandbox.io/s/material-demo-forked-iyng4?file=/demo.js

If you use the code from my suggestion, you will see it'll work =)

Let me know if you have any problems with the example (I haven't use codesandbox for this before)

**Comment by maslianok** [comment]
Aha, I see...

You're trying to implement the approach Dan mentioned in [this comment ](https://github.com/facebook/react/issues/14387#issuecomment-493677168), right?

Does it change the library API? I mean that you can't pass `targetRef` anymore, right? Can you provide a code snippet of how it's intended to be used?

**Comment by whplh** [comment]
Well you probably could make it compatible with targetRef option. ( But i don't really like that, or think it's a good idea =)
I made a pr for what i have in mind, so we can see & discuss changes over [there](https://github.com/maslianok/react-resize-detector/pull/136)

**Comment by maslianok** [comment]
From my point of view:

we have to trigger `useLayoutEffect` when `ref.current` gets changed, but we can't use it as a dependency.

What if we use other props? Let's say

```jsx



// Delay logic
const [isVisible, setIsVisible] = useState(false);
useEffect(() => {
  const timeout = setTimeout(() => {
    setIsVisible(true);
  }, 1000);

  return () => clearTimeout(timeout);
}, []);

const multipleUpdatesRef = useRef();
const { width, height } = useResizeDetector({ targetRef: ref, handleWidth: isVisible });

```

Pay attention to `handleWidth` prop...

**Comment by maslianok** [comment]
So the general idea is to disable resize-detector library when **you know** that your `ref` is empty. And enable it when it's filled with some value...

But it won't work when the `ref` changes... :(

**Comment by maslianok** [comment]
Well, we actually have to pass ref.current as a dependency to `useLayoutEffect`. It will solve all problems...

**Comment by whplh** [comment]
> Well, actually, we have to pass ref.current as a dependency to `useLayoutEffect`. It will solve all problems...

Yes for the cases i tested that would work. But this approach is dicouraged by the react team.

**Comment by whplh** [comment]
> So the general idea is to disable resize-detector library when **you know** that your `ref` is empty. And enable it when it's filled with some value...
> 
> But it won't work when the `ref` changes... :(

Yes. In the use case I encountered the problem the changes came from an library working heavily with async functions, which triggered a delayed ref update.

Yes if you know where the change is coming from like in the example `isVisible` you can add it to the hook.
But in more complicated scenario this might not be the case

**Comment by maslianok** [comment]
Ok, the more I read [that thread](https://github.com/facebook/react/issues/14387) the more I think it's fine to use `ref.current` as a dependency in our particular case.

[This comment](https://github.com/facebook/react/issues/14387#issuecomment-455415008) says there are 2 problems with refs as a dependency:
- there's no guarantee the ref would actually be changed before rendering
- changing the ref doesn't cause a rendering

_Re. the first point:_ yes, it's is a problem for `useEffect`, but we use `useLayoutEffect`. As per the [documentation](https://reactjs.org/docs/hooks-reference.html#uselayouteffect) it fires synchronously **after** all DOM mutations. So it's not a problem for us, right?

_Re. the second point:_ it's true that changing the `ref.current` doesn't trigger an update. But, basically, it should be clear for everyone that React doesn't observe refs and nothing happens when you simply update the ref. And, finally, this problem is much "better" than not processing refs change at all :)


So I would vote to add ref.current as a dependency to `useLayoutEffect`.

**Comment by whplh** [comment]
Ok LGTM, and it's also a simple change in the code.

**Comment by mungojam** [comment]
Similar to the above, I found that I was getting an initial delay before the width and height would get assessed. Using something in the current react docs, I was able to fix it by avoiding `useRef` altogether as they recommend:

```typescript
    const [wrapperRef, setWrapperRef] = useState<
      MutableRefObject<unknown> | undefined
    >(undefined);

    const refCallback = useCallback((node) => {
      setWrapperRef({ current: node });
    }, []);

    const { width, height } = useResizeDetector({
      targetRef: wrapperRef,
    });

    return 
      <div ref={refCallback}>
	<MyBitsUsingWidthAndHeight />
      </div>
```

I wonder if you should do similar. I've asked if they can add an equivalent example to the beta docs, because I might be relying on some legacy ref thing here.
