### ISSUE TITLE
Stray console logs

### ISSUE THREAD

**Issue by JavierM42** [maslianok/react-resize-detector#131]
Hello, I just noticed some stray console logs after I started to use the package. Are these here for a specific reason?

<img width="1266" alt="Screen Shot 2021-02-01 at 13 36 50" src="https://user-images.githubusercontent.com/32175149/106488527-90117c80-6492-11eb-8852-b6a6c79e7b2f.png">

**Comment by whplh** [comment]
Was removed when bumping to in [6.2.1](https://github.com/maslianok/react-resize-detector/commit/da9201dbb2f7f8a7669cc5055de9197f440ef8fa)
Which version do you use?

**Comment by maslianok** [comment]
Yeah, I messed things up a few times in a row :)

But the most recent version from npm shouldn't contain any console.logs.

Let me know if it doesn't work for you
