### ISSUE TITLE
Broken in iOS 11, 12, 13 after updating from 5.2 to version 6.6

### ISSUE THREAD

**Issue by dobesv** [maslianok/react-resize-detector#141]
After we updated to 6.6 users on iOS 11-13 get an error `undefined is not a constructor, evaluating new window.ResizeObserver(n.resizeHandler)`

**Comment by eduard-s** [comment]
+1 on macOS safari - the same issue

**Comment by JaLe29** [comment]
+1 Mobile Safari 12.1, iOS 12.2

**Comment by maslianok** [comment]
Starting from version 6 the library uses `ResizeObserver` without any polyfills since it's supported by all major browsers.

In order the library to work in the older browser versions - please import the polyfilled version from `react-resize-detector/build/withPolyfill`:

```js
import ResizeObserver from 'react-resize-detector/build/withPolyfill';
```

Does it solve the problem?

**Comment by izica** [comment]
+1 macOS safari
`import ResizeObserver from 'react-resize-detector/build/withPolyfill';`

importing withPolyfill doesn't resolve problem

**Comment by izica** [comment]
updating to 6.6.1 resolves the problem

**Comment by maslianok** [comment]
> updating to 6.6.1 resolves the problem

👍

**Comment by altany** [comment]
I get the same error with version `^7.1.2` because of the latest `recharts` upgrade.

**Comment by Semigradsky** [comment]
@altany did you import resize observer polyfill?

**Comment by brunsy** [comment]
Just came across this myself. As the pollyfill was removed in the v7 release...

**Comment by zhibek** [comment]
Confirming I was seeing this problem on `v7.1.2` when using iOS/Safari 12.5.6.

I downgraded to `v6.7.8` so I could import the `withPolyfill` build `react-resize-detector/build/withPolyfill`. That fixed the problem for me.

@maslianok Is there any other solution for this problem when using `v7` of `react-resize-detector`?

**Comment by snelsi** [comment]
@zhibek 
This library uses [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver), which is [supported in >95% of browsers](https://caniuse.com/resizeobserver), so there is no need to polyfill it most of the time. 
If you still need support for old browsers, you can manually add a polyfill, by installing something like [resize-observer-polyfill](https://github.com/que-etc/resize-observer-polyfill) in your project.
