### ISSUE TITLE
HOC pattern type issue when passing props through?

### ISSUE THREAD

**Issue by triblondon** [maslianok/react-resize-detector#142]
I am getting a typescrpipt error:

> Argument of type 'FunctionComponent<Props>' is not assignable to parameter of type 'ComponentType<Omit<unknown, "forwardedRef">>'.

When I do this:

```ts
import CodeEditor from './CodeEditor';
import { withResizeDetector } from 'react-resize-detector';
const ResizableCodeEditor = withResizeDetector(CodeEditor, {});
```

I don't know if it is related, but I also find I cannot invoke `withResizeDetector` with one argument:

```ts
const ResizableCodeEditor = withResizeDetector(CodeEditor);
```

> Expected 2 arguments, but got 1.  An argument for 'options' was not provided.

But the README suggests a one-argument form is valid.

I'm using `react-resize-detector@6.6.1`.  Both problems go away if I downgrade to `5.2.0`.

**Comment by maslianok** [comment]
Should be fixed in 6.6.3
