### ISSUE TITLE
Proposal for documentation

### ISSUE THREAD

**Issue by Primajin** [maslianok/react-resize-detector#145]
When running tests with enzyme and jest after upgrading to v6 I am getting the error:
```
TypeError: window.ResizeObserver is not a constructor
at new ResizeDetector (node_modules/react-resize-detector/src/ResizeDetector.tsx:138:27)
```

I found a similar issue here: https://github.com/que-etc/resize-observer-polyfill/issues/50

I was able to mitigate the error like so:

```typescript
  const { ResizeObserver } = window;

  beforeEach(() => {
    delete window.ResizeObserver;
    window.ResizeObserver = jest.fn().mockImplementation(() => ({
      observe: jest.fn(),
      unobserve: jest.fn(),
      disconnect: jest.fn(),
    }));

    wrapper = mount(
      <MyComponent />
    );
  });

  afterEach(() => {
    window.ResizeObserver = ResizeObserver;
    jest.restoreAllMocks();
  });

  it('should do my test', () => {
    // [...]
  });
```

I just wanted to share this in case questions come up and you'd like to add this to some FAQ or so.

**Comment by maslianok** [comment]
Thank you!

Added to Readme https://github.com/maslianok/react-resize-detector#testing-with-enzyme-and-jest

**Comment by Primajin** [comment]
Sweet thank you
