### ISSUE TITLE
custom targetRef is not working

### ISSUE THREAD

**Issue by brunaschneiders** [maslianok/react-resize-detector#147]
Hi!!

I was trying to use react-resize-detector with a custom ref, like this:

                import React, { useRef } from 'react'
                //
                //
                const targetRef = useRef()
                const { width, height } = useResizeDetector({ targetRef })

I'm receiving an undefined value to width and height.
I saw that are an error with targetRef: 

              Argument of type '{ targetRef: React.RefObject<HTMLDivElement>; }' is not assignable to parameter of type 
                      'FunctionProps'.
              Object literal may only specify known properties, and 'targetRef' does not exist in type 'FunctionProps'.ts(2345)

but I don't know whats the problem...

Do you know how I can solve this problem?

**Comment by maslianok** [comment]
I've created a codesandbox example and everything works as expected

https://codesandbox.io/s/reverent-lewin-u8547
