### ISSUE TITLE
v5.21 + Changelog / Releases Questions

### ISSUE THREAD

**Issue by k-funk** [maslianok/react-resize-detector#155]
I did an `npm audit` on my project today, and `5.20` has a security vulnerability in the lodash dependency. I'd prefer to not bump a major version, and would be nice if there was a `5.21` to handle this with ease.

If that's not possible, is there somewhere you're keeping track of how user can migrate to new major versions? I expect major version bumps to break things, and would rather not be flying blind if I have to do that bump.

**Comment by maslianok** [comment]
Hey @k-funk ,

Sorry for the delayed response. I try to keep all release changes in the **Releases** section https://github.com/maslianok/react-resize-detector/releases

v6 has some major performance improvements so it's highly recommended to update. 
In most cases the update process should not cause any changes to your codebase, but let me know if you face any problems
