### ISSUE TITLE
Set a threshold to skip react render

### ISSUE THREAD

**Issue by mlisthenewcool** [maslianok/react-resize-detector#169]
How should we set a threshold to skip react render under a fixed delta between old and new size ?

```typescript

const MyChild = ({ width, height }: { width: number, height: number }) => {
  return <div style={{ width: width, height: height }}>child content</div>
}

const MyContainer = () => {
  const { width, height ref } = useResizeDetector({})

  return (
    <div style={{ width: '100%', height: '100%' , display: 'flex', backgroundColor: 'blue' }}>
      <MyChild width={...} height={...} />
    </div>
}
```

**Comment by maslianok** [comment]
Sorry for the late answer, I hope you've already resolved the problem, but for anyone coming here with the same question: the library doesn't intend to have built-in utilities for all cases. The main feature of the library is to report when the width or height of the element is changing. It's your choice how to react to these changes. In this case, you should save the prev value, compare it with the new value, and decide what part of your logic should be triggered. Hope it helps.
