### ISSUE TITLE
`onResize` is not as responsive as `window.onresize` does

### ISSUE THREAD

**Issue by EcutDavid** [maslianok/react-resize-detector#18]
Hi @maslianok, thanks for this great lib :)

I forked your code for replicate a issue in my recent project.

It's simply make the square fit to document body while resizing: http://davidguan.me/react-resize-detector/

![image](https://user-images.githubusercontent.com/10692276/33156558-0023471e-d04f-11e7-9ed7-bce92345d2fd.png)

Here is [the code](https://github.com/EcutDavid/react-resize-detector/blob/gh-pages/examples/src/App.js):
```
const s = {
  wrapper: {
    display: 'flex',
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  target: {
    width: 1,
    height: 1,
    background: 'skyblue',
  },
};

class App extends Component {
  state = {
    scale: 1,
  };

  componentDidMount() {
    // window.onresize = this.onResize;
  }

  onResize = () => {
    const PADDING = 60;
    const bodyWidth = document.body.offsetWidth;
    const bodyHeight = document.body.offsetHeight;
    const scale = (bodyWidth > bodyHeight ? bodyHeight : bodyWidth) - (2 * PADDING);

    this.setState({ scale });
  };

  render() {
    return (
      <div style={s.wrapper}>
        <div style={{ transform: `scale(${this.state.scale})`, ...s.target }} />
        <ResizeDetector handleWidth handleHeight onResize={this.onResize} />
      </div>
    );
  }
}
```

In **Safari**, if we drag browser windows to resize it, you can fell the square "jumps", if I simply uncomment `// window.onresize = this.onResize;`, the "jumps" will gone.

**Comment by EcutDavid** [comment]
Also think this discussion maybe is helpful: https://github.com/que-etc/resize-observer-polyfill/issues/9

Thanks!

**Comment by maslianok** [comment]
v.2.0.0 now uses the native implementation with the polyfill mentioned above.
For all updates and suggestions please follow this thread https://github.com/que-etc/resize-observer-polyfill/issues/9
