### ISSUE TITLE
Width is incorrect when device is rotated

### ISSUE THREAD

**Issue by JoshuaVSherman** [maslianok/react-resize-detector#187]
I am on ipad mode in chrome, I am console logging the width, when not rotated it is correct, but when I rotate the device, the width is not correct, am I doing something wrong or is this a bug?
screenshot:
![image](https://user-images.githubusercontent.com/13340120/140929587-e705dbf5-75f2-4d2d-a71c-8fedfd5125dd.png)

link to code example
https://github.com/WebJamApps/CollegeLutheran/blob/develop/src/containers/LiveStream/index.tsx

**Comment by maslianok** [comment]
I copied the source you provided and it seems everything works as expected: https://j7jlz.csb.app/

On the screenshot above you have a separate panel on the right side. I think it's excluded from the container you're observing...

Let me know if you have any additional questions
