### ISSUE TITLE
Error in resize-observer-browser/index.d.ts 

### ISSUE THREAD

**Issue by hamzadigi** [maslianok/react-resize-detector#188]
I am using typescript 4.4.4. When compiling with tsc I'm getting 
`node_modules/@types/resize-observer-browser/index.d.ts(44,27): error TS2304: Cannot find name 'DOMRectReadOnly'.` 

I think it's also related to package resize-observer-polyfill which the last commit is 3 years ago.  Some people forked a new version in this issu https://github.com/que-etc/resize-observer-polyfill/issues/83

**Comment by maslianok** [comment]
'resize-observer-polyfill' removed from the library. 

Published in v7.0.0.

Thank you for the feedback 👍
