### ISSUE TITLE
Use the entry field corresponding to the box model

### ISSUE THREAD

**Issue by kirilldronkin** [maslianok/react-resize-detector#197]
Hi. I'm trying to use `observerOptions` [added in 6.5](https://github.com/maslianok/react-resize-detector/issues/127) to change the box model of observing, but still get the content box dimensions. Looks like the library should decide which entry field ([borderBoxSize](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/borderBoxSize), [contextBoxSize](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize) or [devicePixelContentBoxSize](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/devicePixelContentBoxSize)) use basing on `observerOptions.box`. Maybe a good decision would be move `box` to a separate prop to prevent forgotten memoization of `observerOptions` and further performance penalty, especially considering the fact that it has the only primitive field.

**Comment by maslianok** [comment]
I return to work after some pause and closing old issues to keep the repo clean.
It would be great if we can discuss your concerns above, so feel free to reopen the issue if you are still around.
