### ISSUE TITLE
React resize Detector not woking on old browsers

### ISSUE THREAD

**Issue by codernirmalnp** [maslianok/react-resize-detector#198]
I am running my application in old browers there I got a error of window.resizeDetector is not a constructor error

**Comment by simonshout** [comment]
Just want to +1 this too, can we get an option to use a polyfill?

**Comment by pawelw** [comment]
You should be able to polyfill if needed. Try adding this at the app initialization level. 

```js
import ResizeObserver from 'resize-observer-polyfill';

if (!window.ResizeObserver) {
  window.ResizeObserver = ResizeObserver;
}
```

**Comment by maslianok** [comment]
> You should be able to polyfill if needed. Try adding this at the app initialization level.
> 
> ```js
> import ResizeObserver from 'resize-observer-polyfill';
> 
> if (!window.ResizeObserver) {
>   window.ResizeObserver = ResizeObserver;
> }
> ```

This is the correct answer. Thank you 👍
