### ISSUE TITLE
Handle 'pm' units in addition to just 'px'

### ISSUE THREAD

**Issue by cdaniel** [maslianok/react-resize-detector#20]
Right now, the new dimension is always measured in pixels. Which is good, unless the contained object is variable (f.e. different font sizes). Having a 200 px wide container is acceptable for font 14, but difficult to accept for font 196. It would be good to express the size of the container in any unit relative to a font size.

**Comment by maslianok** [comment]
This component is responsible for notifying you when an element size changes. You can write your own logic to respond to these changes.

I want to keep this component as simple as possible.

I would be happy to reopen this issue for further discussions.
