### ISSUE TITLE
`onFinishResize`?

### ISSUE THREAD

**Issue by softmarshmallow** [maslianok/react-resize-detector#203]
I'm trying to make an optimization logic for render heavy component, only to show while its container is not resizing.

I'm able to trigger start resize event with onResize, but I don't see a feature to listen `onFinishResize` or `onEndResize`

Cheers!

**Comment by maslianok** [comment]
> Yep, there's no `onFinishResize` or anything like that.
> 
> If your problem is you want to avoid the `onResize` being called lots of times in a row while resizing, you can do
> 
> ```js
> useResizeDetector({
>   onResize,
>   refreshMode: 'debounce',
>   refreshRate: 300
> })
> ```
> 
> or something like that.

Correct! Thank you 👍
