### ISSUE TITLE
ReactResizeDetector Component is not working with React18

### ISSUE THREAD

**Issue by pkawula** [maslianok/react-resize-detector#208]
I have found that when installing React 18 the `onResize` prop is not even called when you resize the window, however the  `useResizeDetector` hook works properly.

Here's reproduction
https://github.com/pkawula/resize-example

Remember to install dependencies with `--legacy-peer-deps` to avoid errors

**Comment by maslianok** [comment]
@pkawula thank you for your contributions to the project!

I want to give you some personal prize, but let's stick with the Contributor role for now 😄
