### ISSUE TITLE
Please add typings to make it usable in typescript code

### ISSUE THREAD

**Issue by pmunin** [maslianok/react-resize-detector#21]

**Comment by matthew-matvei** [comment]
Here's something that works for me:
```typescript
/// <reference types="react" />

declare module "react-resize-detector" {

    interface ReactResizeDetectorProps extends React.Props<ReactResizeDetector> {
        handleHeight?: boolean;
        handleWidth?: boolean;
        onResize: (width: number, height: number) => void;
    }

    class ReactResizeDetector extends React.Component<ReactResizeDetectorProps> { }

    export = ReactResizeDetector;
}
```
If the author of this package doesn't want to support it, I could PR this over at DefinitelyTyped

**Comment by maslianok** [comment]
@matthew-matvei 
I'm not an expert in typescript and I would very appreciate if you can create a PR on this.
Let me know if I can help you somehow...

Thanks!

**Comment by matthew-matvei** [comment]
@maslianok 
No worries. You can check out the PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24038)

**Comment by matthew-matvei** [comment]
@maslianok 
The PR is complete, typings for this package are available using `npm install --save-dev @types/react-resize-detector`, so you can close this.

**Comment by lamhieu-vk** [comment]
@matthew-matvei thank you 👍
