### ISSUE TITLE
react resize hook doesn't detect vertical resize

### ISSUE THREAD

**Issue by Ahmed-Dghaies** [maslianok/react-resize-detector#216]
I'm using this library in my react project as a hook and it works very well when i resize the width and height of the window but if i resize the window only vertically it doesn't trigger any events

**Comment by maslianok** [comment]
I'm almost sure there is some problem with block size. For example, it doesn't resize when you resize the window.
It would be great if you can provide a code snippet.

I'll close the issue to keep the repo clean, but we will reopen it once you return.
