### ISSUE TITLE
Return width according to provided observerOptions

### ISSUE THREAD

**Issue by moroine** [maslianok/react-resize-detector#220]
According to the documentation, we can pass ObserverOptions https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe

But when using `box: 'border-box'` the width returned by the hook is always `contentBox`

**Comment by snelsi** [comment]
Created a CodeSandbox of the issue:

https://codesandbox.io/s/nostalgic-dew-egxddl?file=/src/App.tsx

**Comment by Semigradsky** [comment]
Sounds as breaking change

**Comment by moroine** [comment]
It could be an option to select the width to return

**Comment by snelsi** [comment]
Because this issue seems to have been inactive for quite some time now, I'm closing it as stale. 
If you're still encountering this bug in v10, feel free to reopen it.
