### ISSUE TITLE
getComputedStyle can return null in Firefox

### ISSUE THREAD

**Issue by ptvandi** [maslianok/react-resize-detector#23]
There is a bug in Firefox which allows `getComputedStyle` return `null` in an iframe set to `display: none` (see https://bugzilla.mozilla.org/show_bug.cgi?id=548397). In your [ResizeDetector.js](https://github.com/maslianok/react-resize-detector/blob/master/src/components/ResizeDetector.js#L64) component, you can check for null before accessing the `position` property to resolve this issue. This would be a really helpful fix for us, thanks.

```javascript
if (parent.currentStyle) {
  position = parent.currentStyle.position;
} else if (window.getComputedStyle && window.getComputedStyle(parent)) {
  position = window.getComputedStyle(parent).position;
}
```

**Comment by maslianok** [comment]
Should be fixed in v.2.0.0
