### ISSUE TITLE
ResizeObserver loop limit exceeded in v9.1.0

### ISSUE THREAD

**Issue by char0n** [maslianok/react-resize-detector#241]
Hi,

Thanks for great work!

After updating from 8.1.0 to 9.1.0 I've started to see `ResizeObserver loop limit exceeded` error.

![image](https://user-images.githubusercontent.com/193286/236850960-26215e4e-d83a-448d-927c-4d5e2d619da2.png)

 I needed to add  `refreshMode` and `refreshRate` options for application to work as before. 

```js
  const { ref } = useResizeDetector({
    onResize: handleResize,
    refreshMode: 'debounce',
    refreshRate: 0,
  });
```

Affected application: https://github.com/swagger-api/swagger-editor/tree/next

---

This is IMHO very strange as 9.0.0 release notes states that those options are no longer needed.

**Comment by char0n** [comment]
Hi @snelsi, unfortunately I don't think so. I can only reproduce in SwaggerEditor@5 when full codebase is involved. 

Would the dev setup of SwaggerEditor@5 would help you https://github.com/swagger-api/swagger-editor/tree/next#development?

**Comment by Shen120** [comment]
I also encountered this bug, but I did not reproduce it in the demo!
![image](https://github.com/maslianok/react-resize-detector/assets/33613409/c24fc8d1-364a-40e6-b561-2f86010f6eb5)

[This is a Demo](https://codesandbox.io/p/sandbox/heuristic-perlman-4th2g6?welcome=true)

**Comment by hassenc** [comment]
I've noticed I was having infinite re-renders without any errors.
I rolled back to `9.0.0`, it doesn't have the issue

**Comment by snelsi** [comment]
Because this issue seems to have been inactive for quite some time now, I'm closing it as stale. 
If you're still encountering this bug in v10, feel free to reopen it.

**Comment by char0n** [comment]
I haven't seen it in v10.
