### ISSUE TITLE
(Request) pass ref to callback

### ISSUE THREAD

**Issue by tippfelher** [maslianok/react-resize-detector#242]
The callback currently only receives width and height properties.

Some ppl may need the ref returned by the hook in the onResize callback.

**Comment by snelsi** [comment]
Well, I believe it's a relatively easy change to do on our side. 
But in most situations, it's equally easy to get access to `ref` on your side.

Can you provide a small code snippet / codepen of your use case?

**Comment by tippfelher** [comment]
Thank you for your quick response.

1) I don't know how to access ref in my callback here. Can you elaborate please? Thanks! Example:
```typescript
  const onResize = useCallback(() => {
    // access ref.current.getBoundingClientRect() here
  }, []);

  const { ref } = useResizeDetector<HTMLDivElement>({ onResize });
```

2) I solved this by just using a 2nd ref on another element and using resize detection on `ref1` and `getBoundingClientRect` computations on `ref2`, so this issue really isn't urgent for me. But overall `onResize: (ref) => ...` would be less limiting than `onResize: (width, height) => ...` because `ref` would allow us to extract `width`, `hight`, and more `bottom`, `left`, ..

Btw. great hook!

**Comment by snelsi** [comment]
Here you go:

```
// Create your own ref
const res = useRef<HTMLDivElement>(null)

const onResize = useCallback(() => {
    // access ref.current.getBoundingClientRect() here
}, []);

// Pass it as targetRef
useResizeDetector({ onResize, targetRef: ref });
```

**Comment by tippfelher** [comment]
Yey, I just read that again but somehow thought this was not recommended. Evaluated multiple hooks the last hour and seems I read the wrong docs (not the ones for this repo) Thank you and sorry this issue! ^^
