### ISSUE TITLE
Why the onResize fire on first render ?

### ISSUE THREAD

**Issue by rockmandash** [maslianok/react-resize-detector#25]
The onResize will fire at first render.
Is it a browser default behaviour or this is ReactResizeDetector specific behaviour?
Thank you for your hard work!!

**Comment by maslianok** [comment]
You can pass `skipOnMount` property to avoid triggering when a component mounts.

```
<ReactResizeDetector skipOnMount ... />
```

**Comment by rockmandash** [comment]
@maslianok Thank you!
