### ISSUE TITLE
2.0 triggers resize when component unmount

### ISSUE THREAD

**Issue by rockmandash** [maslianok/react-resize-detector#27]
2.0 triggers resize when component unmount
So the resize remain, if you modify props in -onResize, things will break!

**Comment by maslianok** [comment]
Can you provide a code snippet so I can reproduce this issue?

**Comment by rockmandash** [comment]
I thinik I'm wrong.

**Comment by lamhieu-vk** [comment]
@cephirothdy2j hi, please tell me a example code, maybe can I help you ^^

**Comment by matsilva** [comment]
I ran into the same issue and could resolve by calling unobserve in componentWillUnmount.
![image](https://user-images.githubusercontent.com/4511972/37994267-06091b08-31df-11e8-9678-8d0b2b7716e7.png)

Before I did this, I almost did something similar to what the folks behind recharts did https://github.com/recharts/recharts/blob/master/src/component/ResponsiveContainer.js#L71

Notice they are setting a mounted flag to fix this issue.

**Comment by cephirothdy2j** [comment]
Setting the "mounted" flag is what I ended up doing as well.

**Comment by matsilva** [comment]
https://github.com/maslianok/react-resize-detector/pull/32 @cephirothdy2j  can you build and test in your project to see if this works?

**Comment by cephirothdy2j** [comment]
Yes, that PR appears to resolve the issue. 👍

**Comment by matsilva** [comment]
> Yes, that PR appears to resolve the issue. 👍

Thanks for checking it out.

**Comment by maslianok** [comment]
Thanks to everyone for your involvement!

@matsilva Huge thanks for the PR! :)

**Comment by maslianok** [comment]
react-resize-detector@2.3.0 published to npm with this fix!

**Comment by matsilva** [comment]
> react-resize-detector@2.3.0 published to npm with this fix!

Awesome! Thanks a lot.
