### ISSUE TITLE
Render prop option

### ISSUE THREAD

**Issue by natew** [maslianok/react-resize-detector#33]
This would save some code for me:

```
<ReactResizeDetector render={({ width, height }) => <MyComponent width={width} />}
```

**Comment by lamhieu-vk** [comment]
hi @natew ,
what would you use `render-props` for? can you give the example dark? if it is necessary I will find how to optimize it and create a pull request! :D

**Comment by natew** [comment]
It avoids needing to "setState" to store the width/height, which means no need to have a class you can just do a small function! So saves me 12 lines of code and complexity or so.

**Comment by lamhieu-vk** [comment]
okey, I would consider and create a pr for new feature!

**Comment by maslianok** [comment]
There is another pattern which is very popular nowadays and which is perfectly fitting this feature:

```
<ResizeDetector>
  {(width, height) => <MyComponent width={width} />}
</ResizeDetector>
```

I think it's a little bit more clear and has a better formatting. One of the very popular libraries that uses this notation is Apollo https://www.apollographql.com/docs/react/essentials/queries.html#basic

So I'm in favor of this approach...

------

From the technical side I would say that we can use Fragment to not add any extra tag to the DOM tree
```
const { children } = this.props;
return (
  <React.Fragment>
    <div style={styles}.../>  // our helper
    {children && typeof children === 'function' && children(width, height)}
  </React.Fragment>

);
```

**Comment by lamhieu-vk** [comment]
if we use Fragment is package still support project use React version older?
I think use Fragment and render children is best way!

**Comment by maslianok** [comment]
I think we can bump a new release and mention that it supports only React 16+

**Comment by lamhieu-vk** [comment]
I don't think supports only React 16+ is best way, because `render props` just a feature, I think we can use `render props` instead of using `Fragment`, and if want use children render we can clone a children handle and return it!

**Comment by maslianok** [comment]
I'm not sure that I understood your idea...
It would be great if you can make a PR with this implementation.

**Comment by lamhieu-vk** [comment]
@maslianok okey, I will implementation it and make a pr soon!

**Comment by lamhieu-vk** [comment]
hi @maslianok ,
you can add me to collaborators in this package in npm so I can develop it?
thank you very much.

**Comment by lamhieu-vk** [comment]
hi @natew,
a updated `react-size-detector` can render children at commit https://github.com/maslianok/react-resize-detector/commit/f118503a5955718ca3c67067d487c004f2dd5a1f
you can read example in readme

**Comment by maslianok** [comment]
@natew deployed in v3.0.1
