### ISSUE TITLE
More patterns ? (render-prop maybe) ?

### ISSUE THREAD

**Issue by cyrilchapon** [maslianok/react-resize-detector#38]
I love this component and use it actively.

Maybe more patterns would make it even more flexible?

I can think of two :

- HOC (which is basically wrapping child-component inside a function)
- Render-prop (which is basically the same as children-as-function, with the same function in another prop)

**Comment by cyrilchapon** [comment]
@lamhieu-vk did you read the message ?

I was not asking for help here, but rather suggesting the addition of more [patterns](https://github.com/maslianok/react-resize-detector#examples), like [HOC](https://reactjs.org/docs/higher-order-components.html) or [render-prop](https://reactjs.org/docs/render-props.html) which are the most used one I believe.

**Comment by maslianok** [comment]
@cyrilchapon Thanks for your suggestions!

Let me clarify your suggestions.

1. HOC
```
class MyComponent extends Component {
...
}

export default withResizeDetector(MyComponent);
```
and, as a result, MyComponent will be updated each time it resizes, right? It's a great suggestion. I like it.

2. I'm not sure that I understand this one. Can you please provide a code snippet of the desired usage?

**Comment by lamhieu-vk** [comment]
@cyrilchapon  I have a reference for you,  [rc-target-size](https://github.com/lamhieu-vk/rc-target-size)! but these two components have different uses, you can use [rc-target-size](https://github.com/lamhieu-vk/rc-target-size) when just get the `size` or `offet` of the **child element**, not **parents**. it supports the render props (children), component and hoc.

I did not suggest how the `rc-target-size` works on `react-resize-detector` because I think it will change its original structure!

**Comment by cyrilchapon** [comment]
@maslianok 

1. HOC

> 
> ```
> class MyComponent extends Component {
> ...
> }
> export default withResizeDetector(MyComponent);
> ```

> and, as a result, MyComponent will be updated each time it resizes, right?

Yeah, precisely that. That's no more than [child component pattern](https://github.com/maslianok/react-resize-detector#child-component-pattern) with syntactic sugar.

> It's a great suggestion. I like it.

I'm personaly not a fond of this pattern, as I tend to follow trends, and it's a bit discouraged nowadays, in favor of...

2. Render props

> I'm not sure that I understand this one. Can you please provide a code snippet of the desired usage?

Well, this is basically the same as [Child Function Pattern](https://github.com/maslianok/react-resize-detector#child-function-pattern) from the Component point of view, except it reads the function from a `render` prop, and not from a `children` prop.

From the consumer point of view, this is the following

```
<ReactResizeDetector
  handleWidth
  handleHeight
  render={(width, height) => <div>{`${width}x${height}`}</div>}
/>
```

(in fact, I can't remember if the function would be passed th

**Comment by maslianok** [comment]
Added in v3.1.0.

@cyrilchapon Thanks for suggesting this! 🥇

**Comment by cyrilchapon** [comment]
This sounds fantastic. I'll surely test render prop one tomorrow 🤙☺️
