### ISSUE TITLE
Doesn't detect table resizes

### ISSUE THREAD

**Issue by maxhudson** [maslianok/react-resize-detector#4]
```
<Table>
  <ReactResizeDetector handleWidth handleHeight onResize={this.handleResize}/>
  {rows}
</Table>
```
Table is `display: table`
Rows are each `display: table-row`

When a cell within a row resizes (I've got inputs in table-cells), the size of the `ReactResizeDetector` `div` changes, but no event is fired. The width of the RRD `div` is the correct value.

`this.handleResize` is bound in the constructor: `this.handleResize = this.handleResize.bind(this);`. It simply doesn't get called except for when the table first renders.

**Comment by maslianok** [comment]
This example works fine for me

```jsx
<table>
  <ResizeDetector handleWidth handleHeight onResize={() => console.log('Resized')} />
  <tr>
    <td>test</td>
  </tr>
</table>
```

You are using some custom `table` component and this may be the source of errors.
RRD tries to set `position: relative` to the parent element under the hood. The library doesn't work without this property.
