### ISSUE TITLE
Auto test for package

### ISSUE THREAD

**Issue by lamhieu-vk** [maslianok/react-resize-detector#42]
I think package should have a CI and test cases to easier enhancement it in future!

**Comment by maslianok** [comment]
Great idea, @lamhieu-vk 

Can you help me with this?
I think we should create a separate fork and setup everything there. When we confirm that it works for us - we will move everything to this repo.

What do you think?

**Comment by lamhieu-vk** [comment]
I think I can help you create a basic test case (test render component) for package
but I think I don't have permission to add CI auto test when PR or commit to project

**Comment by maslianok** [comment]
Well, you can fork the repo and setup everything there. When you prove that it works - you can make a pull request to transfer all logic in the master repo.

I'm closing this issue for now.
If/When you have time to integrate this - please open a separate issue or PR.

Thanks again for being proactive and suggesting this feature. Hope we will make it work... someday :)
