### ISSUE TITLE
Debounce mode causes "Can't call setState (or forceUpdate) on an unmounted component."

### ISSUE THREAD

**Issue by VoronFX** [maslianok/react-resize-detector#43]
Delaying onResize call with debounce can invoke setState on an unmounted component which causes warning from React.
Will be nice to add guard for this case.

**Comment by maslianok** [comment]
@VoronFX Thanks for describing this bug!

Fixed in v3.1.2

**Comment by OZZlE** [comment]
@maslianok how did you fix it? :) I'm having the same issue in my own component, I still want to keep the throttle and not use `isMounted` as it's deprecated :(

**Comment by VoronFX** [comment]
@OZZIE
You can use set something like 'isUmounted' to true in 'componentWillUnmount'. That one is not deprecated.

**Comment by OZZlE** [comment]
@VoronFX I tried this but still got this anyway, maybe it was from some other component.. I don't know, I'm just ignoring it for now as it only happens on browser resize and never otherwise..
