### ISSUE TITLE
Use of <div> fails validateDOMNesting check in certain elements

### ISSUE THREAD

**Issue by exogen** [maslianok/react-resize-detector#48]
(xposting to `react-size-observer` as it's an issue there as well ☹️)

Apologies if someone has brought this up before. I've tried both `react-resize-detector` and `react-resize-observer`, and I'm using them in a way where I need it to live inside elements like `<p>` and `<span>` sometimes.

But React complains about this since it's against the HTML spec:

```
index.js:2178 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```

It seems like the same functionality could be done with `span` as long as it's set to `display: block`. AFAIK spans are valid everywhere. Would it be worthwhile to switch?

**Comment by maslianok** [comment]
Hi @exogen ,

Thanks for this suggestion.
To be honest I'm afraid that this change will break something :) 

I suggest to test it a bit before push a new release to npm. Can you maybe fork the repo, make this change and test it in your app?
You need to change 1 line of code in `src/index.js` 
<img width="514" alt="screen shot 2018-11-13 at 3 10 31 pm" src="https://user-images.githubusercontent.com/3485490/48415639-981c5f00-e756-11e8-8bb1-6b8a732f0ede.png">

wdyt?

**Comment by ai212983** [comment]
I'd suggested to make this configurable, because spans are NOT valid everywhere (try to put them into 'table', for example)

**Comment by maslianok** [comment]
hmmm...
We can use [React.createElement](https://reactjs.org/docs/react-api.html#createelement) feature to create a configurable react element. Instead of using a hardcoded `div` element.

And we can pass the node type as a prop, right?

It will look like this
```
<ReactResizeDetector nodeType="tr" ... />
// or
<ReactResizeDetector nodeType="span" ... />
```

I think it may work. Thanks for the idea, @ai212983 !
Can someone make a PR on this?

**Comment by maslianok** [comment]
Thanks everyone for discussion and ideas.

Deployed in v3.4.0.

Use `nodeType` prop to change the node's type. `div` by default.
