### ISSUE TITLE
Resize event only triggering on larger viewport then initial load?

### ISSUE THREAD

**Issue by nealoke** [maslianok/react-resize-detector#5]
Hi, I'm trying to use your component for determining the height of the document. Using the following code to log the width and height in the console to make sure everything is correct. The `ReactResizeDetector` is at the top of my app rendering structure. So should fire always (also when content inside changes).

```
onResize(height, width) {
	console.log(height, width);
}
```

However when testing it, the onResize event only fires when the viewport is larger than the one initially loaded. o.O

See GIF here
![resize](https://cloud.githubusercontent.com/assets/17417414/21555367/e07f2502-ce17-11e6-9be1-46910c4eb119.gif)

**Comment by maslianok** [comment]
Unfortunately, I can't reproduce this bug.

Can you provide some example to reproduce this error?

**Comment by nealoke** [comment]
@maslianok no worries, i've switched over to element-resize-event which worked fine.
