### ISSUE TITLE
How to watch 'window' resize with this?

### ISSUE THREAD

**Issue by 0xdevalias** [maslianok/react-resize-detector#50]
I tried a couple of ways to try and make `resizableElementId ` specify the window, but I could make it work. Is it possible to watch window resize events with this? It would be nice to be able to make use of the debounce/other features built in.

**Comment by PascalSenn** [comment]
I'm not sure what you are trying to achieve, but if you just try to trigger an event on window resize, you can just use an event listener on window.
`window.addEventListener("resize", (...args) => console.log(args))`

**Comment by maslianok** [comment]
Yes, exactly.

JS has a built-in method to handle [window resizes](https://developer.mozilla.org/en-US/docs/Web/Events/resize)

Nevertheless, you can attach `react-resize-detector` to a root element, e.g. to the '#app' in the next example
```
<body>
  <div id="app">...</div>
</body>
```
