### ISSUE TITLE
handleHeight broken ?

### ISSUE THREAD

**Issue by qvanderlinden** [maslianok/react-resize-detector#54]
Hi,

I am using react-resize-detector version 3.2.1 and it seems like no resize event is thrown when I resize my browser window vertically, even though handleHeight prop is set to true.

Here is my code:
```
<ReactResizeDetector
  handleWidth
  handleHeight
  onResize={(width, height) => {
    console.log("resize detected")
    updateMapboxViewport({ width, height })
  }}
>
  <ReactMapGL
    attributionControl={false}
    mapStyle={mapboxStyle}
    mapboxApiAccessToken={mapboxToken}
    {...mapboxViewport}
    onViewportChange={updateMapboxViewport}
  >
    <DeckGL {...mapboxViewport} layers={layers} />
  </ReactMapGL>
</ReactResizeDetector>
``` 

In the following video, you can see that "resize detected" is logged to the console when I resize the browser window horizontally, but not when I resize it vertically.

[react-resize-detector.webm.zip](https://github.com/maslianok/react-resize-detector/files/2621269/react-resize-detector.webm.zip)

Thanks in advance,
Quentin

**Comment by maslianok** [comment]
@qvanderlinden 
It works well if you put `div` or `span` inside the ReactResizeDetector.

Maybe (just a hypothesis) `ReactMapGL` returns some non-standart DOM element. For example, svg or canvas and ResizeObserver doesn't work with such element...

**Comment by qvanderlinden** [comment]
Thanks for your reply, I just managed to make it work. I think I was not using it how it is intended to. I made it work with the following code

```
const WrapperDiv = styled.div`
  position: absolute;
  width: 100%;
  height: 100%;
`

const Map = ({
  mapboxStyle,
  mapboxToken,
  mapboxViewport,
  updateMapboxViewport
}) => (
  <WrapperDiv>
    <ReactMapGL
      attributionControl={false}
      mapStyle={mapboxStyle}
      mapboxApiAccessToken={mapboxToken}
      {...mapboxViewport}
      onViewportChange={updateMapboxViewport}
    >
      <AnimatedActivities mapboxViewport={mapboxViewport} />
    </ReactMapGL>

    <ReactResizeDetector
      handleWidth
      handleHeight
      onResize={(width, height) => updateMapboxViewport({ width, height })}
    />
  </WrapperDiv>
)
```

**Comment by maslianok** [comment]
Thanks!

Yes, when you put ReactResizeDetector inside `div` it works great.

Your previous example should work as well, but maybe ReactMapGL component has some fancy logic and it prevents ReactResizeDetector from injection inside it.

Great that you found a workaround for this 👍
