### ISSUE TITLE
"Error: Element type is invalid" when using callback pattern

### ISSUE THREAD

**Issue by 1n1t** [maslianok/react-resize-detector#56]
Hi there.

I'm trying to use your library to fire an event when one of my component has been resized, but I'm getting a weird error from React.

Here is my implementation:
```js
render() {
    return (
            <div className="AuthForm">
                <MyStuff />
                <ReactResizeDetector onResize={ this.onResize }/>
            </div>
        );
}
```

and here is the error that I'm getting:

```js
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `AuthForm`.
```

What am I doing wrong? Or is it an issue with the lib?
Thanks for help

**Comment by maslianok** [comment]
Hi @1n1t 

Thanks for reaching me out.
The only explanation I have is that you have some problems with your **AuthForm** component. Probably it returns `undefined` or any other non-valid structure. It must return string or class/function or `null`.

I don't think it's a problem with react-resize-detector. Please try to remove `<ReactResizeDetector onResize={ this.onResize }/>` and let me know if the problem reappears.

**Comment by unski11ed** [comment]
This, or similar error can occur when you are using React 15 (probably by the render props option). Downgrade `react-resize-detector` to 2.X to resolve the issue. Seems to work ok for me now.

**Comment by 1n1t** [comment]
> Hi @1n1t
> 
> Thanks for reaching me out.
> The only explanation I have is that you have some problems with your **AuthForm** component. Probably it returns `undefined` or any other non-valid structure. It must return string or class/function or `null`.
> 
> I don't think it's a problem with react-resize-detector. Please try to remove `<ReactResizeDetector onResize={ this.onResize }/>` and let me know if the problem reappears.

Thanks for your reply @maslianok 

Actually, when I comment out `<ReactResizeDetector onResize={ this.onResize }/>` everything works just fine. That's why I thought there might be a problem in your package. Can you take a look at it one more time?

**Comment by maslianok** [comment]
The error says that you return object from the `AuthForm` component.
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

As you can see, the RRD render method return array
```
...
return [resizeDetector, this.handleRenderProp(), ...this.renderChildren()];
```

This feature was added in React v16. So it can be a problem if you use React < v16. Try to downgrade RRD as @unski11ed suggested above

**Comment by 1n1t** [comment]
> This feature was added in React v16. So it can be a problem if you use React < v16. Try to downgrade RRD as @unski11ed suggested above

Yeah, I use React v16.6.3, so the cause is not the package version. Could it be because I use server side rendering?
