### ISSUE TITLE
Add support for leading/trailing option for throttle and debounce.

### ISSUE THREAD

**Issue by Biohazord** [maslianok/react-resize-detector#57]
Would you be interested in a PR to add an additional prop for the leading/trailing options for Lodash's throttle/debounce function? If yes, I can whip something up.

**Comment by maslianok** [comment]
Hi @Biohazord 
Thanks for the suggestion!

Deployed in [v3.3.1](https://www.npmjs.com/package/react-resize-detector)
Added `refreshOptions` prop: 
```
{ leading: bool, trailing: bool }
```
