### ISSUE TITLE
Support for different selectors and/or multiple selectors

### ISSUE THREAD

**Issue by nimi** [maslianok/react-resize-detector#58]
Hi @maslianok!

Thanks for the very cool lib!

Right now this library only supports adding a resize detector on a parent element or a `resizableElementId`. It would be nice if this were a bit more flexible and it would allow both a way to provide a selector that is not only just `id` (for example using `querySelector`) and allow for more than one selector to be added and I can listen to resize events on multiple elements. Thoughts?

**Comment by maslianok** [comment]
@nimi 
v4 introduces `querySelector` props

**Comment by nimi** [comment]
Awesome. Thanks @maslianok
