### ISSUE TITLE
unexpected scrollbar in chrome & safari & mac 

### ISSUE THREAD

**Issue by neekey** [maslianok/react-resize-detector#6]
Hi, I'm using Recharts to implement some cool charts and using its responsive-container to make all the charts responsive, but I encountered some weird unexpected scrollbar inside the chart while resizing:

![image](https://cloud.githubusercontent.com/assets/499870/22089381/e03386c4-de3e-11e6-8609-bb35a17c63fe.png)

I inspected the HTML a little bit, and it's not related to SVG or recharts itself, it's actually caused by the DIVs that [react-resize-detector creates](https://github.com/recharts/recharts/blob/master/src/component/ResponsiveContainer.js#L136).

So currently I just work around this issue to force all the divs that react-resize-detector creates to have the CSS style:

```
overflow: hidden
```

I am not sure why does this happen but looks like it begins after a ancestry element got the flex layout ( `display: flex` ).

Anyway, just let you know the issue, and also I kind of want to know why you have to use `overflow: scroll`.

**Comment by justinpincar** [comment]
I'm running into this same issue. What was your specific fix / where did you put that css?

**Comment by nickuraltsev** [comment]
@justinpincar Here is what worked for me:

```css
.recharts-responsive-container div {
  overflow: hidden !important;
}
```

**Comment by justinpincar** [comment]
@nickuraltsev Seems to work well - thank you very much!

**Comment by jasonrhodes** [comment]
Does anybody have an idea of what a solution would be so that folks don't have to add `!important` CSS into their styles? I'm not familiar with the project but if someone has a clue/idea of where to look, I'd be happy to help track it down and submit a fix.
