### ISSUE TITLE
Refactor for package

### ISSUE THREAD

**Issue by lamhieu-vk** [maslianok/react-resize-detector#60]
hi @maslianok 
Long time no see, I have maintained and contributed to some projects, so far I think it is time we need a major update on the performance and problems of this library. Can I refactor new version for lib using ref of React to wrap component instead of adding a new element and improve performance for lib? Maybe this is a big update for lib!

**Comment by maslianok** [comment]
hey @lamhieu-vk 
Glad to see you again :)

Yes, sure! It would be very helpful!

**Comment by lamhieu-vk** [comment]
@maslianok thank you, I make a PR soon!

**Comment by maslianok** [comment]
Big thanks @lamhieu-vk for leading this refactoring! 
Awesome suggestions and awesome quality of code! Thanks!

**Comment by lamhieu-vk** [comment]
@maslianok I really happy when read your comment, nice to be the maintainer of the project in the future!
