### ISSUE TITLE
Warning in StrictMode

### ISSUE THREAD

**Issue by infodusha** [maslianok/react-resize-detector#68]
`Warning: findDOMNode is deprecated in StrictMode. ... Instead, add a ref directly to the element you want to reference.`
Would be a version with ref support?

**Comment by maslianok** [comment]
Hi @infodusha 

We have to use findDOMNode in order to find an observable DOM element.

The code is located here https://github.com/maslianok/react-resize-detector/blob/master/src/components/ResizeDetector.js#L84

We can't simply use a reference, because it can be a React Component, not a DOM element

**Comment by maslianok** [comment]
However, I hate all these warnings so in version 4.1.0 I added `targetDomEl` property :)

The library doesn't use the `findDOMNode` method when you pass this property.

For example:

Before (findDOMNode is used)
```
  render() {
    return (
      <div>
        ...
        <ReactResizeDetector handleWidth handleHeight />
      </div>
    );
  }
```

After (without findDOMNode)
```
  constructor() {
    this.parentRef = React.createRef();
  }
  render() {
    return (
      <div ref={this.parentRef}>
        ...
        <ReactResizeDetector handleWidth handleHeight targetDomEl={this.parentRe.current} />
      </div>
    );
  }
```

Yes, you have to add an extra prop, but this should remove the annoying warning from a console.

**Comment by maslianok** [comment]
https://github.com/maslianok/react-resize-detector/releases/tag/v4.1.0

**Comment by infodusha** [comment]
Thx! Nice job)

**Comment by richardoptibrium** [comment]
It's not working for me unfortunately. I'm using v4.2.1

**Comment by emilyjablonski** [comment]
Upgraded to ^5.0.6 and am using the `targetDomEl` prop above and still receiving this error

**Comment by emilyjablonski** [comment]
https://github.com/maslianok/react-resize-detector/issues/72 Try upgrading to 5 and using the new targetRef prop
