### ISSUE TITLE
.babelrc file 

### ISSUE THREAD

**Issue by jabaren** [maslianok/react-resize-detector#7]
Hi,
I'm not quite sure if it's an issue, but the .babelrc configuration is breaking my own .babelrc configuration, also jenkins is sending the same error.

The error that I got is this: Couldn't find preset "es2015" relative to directory "/xxx-xxxt/node_modules/react-resize-detector"

is there any way to avoid the manually delete?

Thanks.

**Comment by maslianok** [comment]
Should be fixed after https://github.com/maslianok/react-resize-detector/pull/8
