### ISSUE TITLE
Debug `console.log` present in npm

### ISSUE THREAD

**Issue by robcmills** [maslianok/react-resize-detector#74]
- I just upgraded to react-resize-detector@4.1.1 using yarn
- I dropped a ReactResizeDetector into my component tree
- Observed in the console `ResizeDetector.js:178` logging the word `parent` on every resize
- Confirmed in the Sources panel there is indeed a log statement in 
  `node_modules/react-resize-detector/lib/esm/components/ResizeDetector.js:178`

I don't see this log statement in the repo currently. Is it possible that the bundle published to npm is out-of-date?

**Comment by robcmills** [comment]
<img width="484" alt="Screen Shot 2019-06-04 at 1 59 39 PM" src="https://user-images.githubusercontent.com/4131746/58913482-26dfd180-86d1-11e9-8513-24ba405349fa.png">

<img width="1174" alt="Screen Shot 2019-06-04 at 1 45 01 PM" src="https://user-images.githubusercontent.com/4131746/58913516-38c17480-86d1-11e9-88b4-89fdd01e89c3.png">

**Comment by maslianok** [comment]
Hi @robcmills 

Please upgrade to the latest version 4.1.4.

The bug you describing was fixed in this commit https://github.com/maslianok/react-resize-detector/commit/c77c74a0d3405d8a863dd95b7acafdeb63844588 2 months ago and deployed in version 4.1.2

**Comment by robcmills** [comment]
@maslianok 

Yes that resolved it! 👏 

Thanks for replying.
