### ISSUE TITLE
Add looser peer dep requirements for react and react-dom?

### ISSUE THREAD

**Issue by majapw** [maslianok/react-resize-detector#75]
QQ: Would it be possible to loosen the `react` and `react-dom` peer dep restrictions to `^16.0.0` or are there explicit dependencies on react 16.8+ features in this library?

**Comment by maslianok** [comment]
yes, I don't see any reason why it can't be ^16.0.0.

We use child arrays, but this feature was added in ^16 https://css-tricks.com/render-children-in-react-using-fragment-or-array-components/#article-header-id-4

Let me update dependencies

**Comment by maslianok** [comment]
Fixed in this commit https://github.com/maslianok/react-resize-detector/commit/8555cc46c03a25ca5ffb207aed7f2cc0d1fe019b

Released in v4.2.0

Thanks for the suggestion, @majapw 👍

**Comment by majapw** [comment]
Thank you @maslianok! :)
