### ISSUE TITLE
Avoid render again on google maps fullscreen

### ISSUE THREAD

**Issue by velthune** [maslianok/react-resize-detector#77]
As in title, `ResizeDetector` is triggered on Google maps component fullscreen which causes a re-render.

How can avoid this behaviour?

**Comment by maslianok** [comment]
Well, this should be an internal solution.

IMO, it's expected that fullscreen mode triggers a re-render. If you want to avoid this - please set some flag before you go to fullscreen mode and disable/remove react-resize-observer based on that flag

**Comment by maslianok** [comment]
Also, it's possible that you're referring to the bug described in #78. In such case please refer to the discussion there
