### ISSUE TITLE
Paddings and borders ignored.

### ISSUE THREAD

**Issue by blackbird91** [maslianok/react-resize-detector#89]
Hi,

I've just added this package in our website to measure the header height because it has a variable height based on the region site is accessed from. I saw that paddings and borders are not  part of the height computed by this package. Is this intended? Can we have some additional props that will allow us to include also these values?

Thanks

**Comment by maslianok** [comment]
Hi @blackbird91,

Great question.

Let me try to explain:
Inside the library we use the [`contentRect`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentRect)  to handle width/height. This is already supported by many browsers and, in addition to this, we use a polyfill for the browsers where this data isn't available.

Resize Observer also describes [`contentBoxSize`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize) prop that may resolve your problem, but, unfortunately, it's not supported by major browsers.

I'd suggest you use `react-resize-detector` as a trigger that the header was resized and measure width/height from inside the method:

```
constructor() {
  this.headerRef = React.createRef();
}
onResize = () => {
    const width = this.headerRef.getBoundingClientRect().width;
    // ...
};
render() {
    return (
      <div ref={this.headerRef}>
        // ....
        <ReactResizeDetector handleWidth onResize={this.onResize} />
      </div>
    );
  }
```

Or you can do the same inside functional components using `useEffect`/`useRef`
