### ISSUE TITLE
JFYI: TypeScript

### ISSUE THREAD

**Issue by Diokuz** [maslianok/react-resize-detector#97]
Because of breaking changes in 5, we had an issue in production after automatic update. We failed to prevent it, because we use outdated https://www.npmjs.com/package/@types/react-resize-detector

Consider to use typescript instead of js in this rep.

**Comment by maslianok** [comment]
Thanks, @Diokuz 

It would be great if anyone can help me to update `@types/react-resize-detector`

**Comment by jmadankumar** [comment]
@maslianok I can help you with updating the types

**Comment by jmadankumar** [comment]
@maslianok I can help you with update of @types/react-resize-detector.  As per the documentation we need to remove querySelector, nodeType, and targetDomEl prop types from the typescript definition file. Please confirm whether my understanding is right about the latest changes

**Comment by maslianok** [comment]
@jmadankumar thanks for your help.

These lines describe all available props https://github.com/maslianok/react-resize-detector/blob/master/src/components/ResizeDetector.js#L200-L217

`querySelector`, `targetDomEl` and `nodeType ` are still there. I removed them from the documentation but still keep them in the code to not break any existing logic. I'm not sure whether we should remove it from TS or not. Let's maybe keep them for now? What do you think? (I would vote to remove them in the next major release)

Other than that it looks great! Thanks for your effort 👍

**Comment by jmadankumar** [comment]
@maslianok As the props are still supported by the library. we should keep the props in the documentation. as well as in the TS. In the next major release, we will remove props from documentation as well as TS.

**Comment by maslianok** [comment]
Ok, agree. I’ll add the props back and mark them as deprecated.

So now you can create a PR without removing these props

**Comment by jmadankumar** [comment]
@maslianok I will create PR mark the props deprecated in the TS

**Comment by jmadankumar** [comment]
@maslianok Created the PR for the types changes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47098

**Comment by maslianok** [comment]
Approved! Thank you 👍

**Comment by jmadankumar** [comment]
@maslianok [@types/react-resize-detector v5.0.0](https://www.npmjs.com/package/@types/react-resize-detector) published to NPM
